### PR TITLE
Ad blocker Warning Message

### PR DESCRIPTION
**Pull request by cqx931**
https://github.com/dhowe/AdNauseam/issues/546

### CODE REVIEW

**Comment by dhowe** [comment]
@cqx931 please use correct formatting

**Comment by dhowe** [comment]
also, we cannot ever include any chrome.* calls in the code, at least without a check first, or it will crash on firefox and other browsers

**Comment by cqx931** [comment]
yes, I know that this should be handled separately in Chrome and Firefox.
Should this chrome.management call goes to vAPI-client?

**Comment by dhowe** [comment]
correct... but for now just add a conditional check (do a search for 'chrome' in src and you will find another similar case)

**Pull request merged**
