### PR TITLE
fix to the parsing of target urls 

### PR DESCRIPTION
**Pull request by greysonevins**
Should help with issue #1099 and #963

### CODE REVIEW

**Comment by dhowe** [comment]
why are we accepting ftp addresses?

**Comment by greysonevins** [comment]
@dhowe  @cqx931 
I can make the changes, but I was thinking a bit more about the issue and wondered if we should do a regular expression to test if the URL ends in a tLD (.com/.de/etc).
 
Some of the ads I picked up from the fmovie website were not full links (e.g. "https://You_Better_Close_The_Door_Before_You_Play_This_Game", so the ads failed when clicking. Should we just reject these ads entirely?

**Comment by dhowe** [comment]
makes sense... you can add this check to validateTarget(ad) in core.js (~line 620).

**Comment by greysonevins** [comment]
You can see in this test that the updates will delete ```"id": 8,``` but before the update, it will get stuck on pending for this one. 
[test.json.zip](https://github.com/dhowe/AdNauseam/files/1171837/test.json.zip)

**Pull request closed without merging**
