### PR TITLE
Help button added to vault

### PR DESCRIPTION
**Pull request by greysonevins**
Fix for #1081

### CODE REVIEW

**Comment by greysonevins** [comment]
image

**Comment by dhowe** [comment]
why a star when everywhere else we used the  '?'  
thoughts, @mushon?

**Comment by greysonevins** [comment]
The help-mark class has style set for green, I could go in and edit that styling specifically for the showing
image

or I could set it to an information icon.
image

**Comment by dhowe** [comment]
Lets move discussion back to the ticket

**Pull request closed without merging**
