### PR TITLE
Implement user settings backup

### PR DESCRIPTION
**Pull request by cqx931**

### CODE REVIEW

**Comment by dhowe** [comment]
Fixes:
'ads' should be uppercase 'Ads' in export dialog:

image

**Comment by dhowe** [comment]
Question: what is 'last restore' supposed to show?

image

**Comment by cqx931** [comment]
According to our last discussion, "Export" and "Import" in vault only import and export ads. And I haven't changed the code for the "import" button yet.
If we want to be clear about it I would suggest:
1.Change the buttons in vault to "Export Ads" and "Import Ads"
2.The "Import Ads" button takes two format: ads only and settings and ads, but it only modifies the ads and ignores the settings.
3.If the user tries to import settings only file(and maybe also for other random files?), the warning text shows "The file doesn't contain any Ad, please choose another file."

**Comment by cqx931** [comment]
This is what  'last restore' supposed to show in ublock. I can fix it in the next commit.
Two questions:
1. Last backup time is a bit confusing in our case(three formats, and the file could also come from the vault), could we hide this information?
2.Should we use "Back up to file" and "Restore from file" instead of "Export" and "Import" to differentiate it with the buttons from the vault?

image

**Comment by cqx931** [comment]
Please check the new commit.

Fixed the following issues:
1. Different filenames for 3 input types 
1. No first-run page after settings restore
1. Fixed 'export' button in vault
1. Fixed 'Import' in vault as suggested above
1. Uppercase 'Ads' in export dialog

**Comment by dhowe** [comment]
1. Export dialog appears at strange location (very bottom of screen)


image

1. Import of settings/ads in vault gives the following unclear message:

image

**Comment by dhowe** [comment]
@cqx931 let me know when this is ready to be merged...

**Comment by cqx931** [comment]
All fixed. ready to be merged.

**Pull request merged**
