### PR TITLE
#436 CSS changes for whitelist.html

### PR DESCRIPTION
**Pull request by leoneckert**
This puts the changes in @dhowe asked for in https://github.com/dhowe/AdNauseam/issues/436 (if I understood them correctly). 

I'd feel more confortable if @mushon would verify, so this is not completely out his CSS logic. 

**What I did**: modified aspects of the global #lists, .geName, .geCount, .groupEntry and .listEntry inside whitelist.css (which only applies to whitelist.html), so that styles on other pages are not affected.

screen shot 2016-09-30 at 20 17 07

### CODE REVIEW

**Comment by mushon** [comment]
Looks good. Thanks.
One question though, shouldn't the. Buttons be under the text field? Don't the my confirm the actions there rather than only the one checkbox?
Otherwise, I will continue to check and if something comes up I will report in another ticket.

**Comment by dhowe** [comment]
Yes, the original uBlock design has the buttons on top, but it was the only thing on the page... I had suggested extra space to separate two separate functionalities (external and internal whitelists);  moving the buttons to the bottom might achieve the same effect, and/or some kind of visual indicator they are distinct

**Comment by leoneckert** [comment]
should I make more changes on that? If moving them to the button, should they then be right next to the other buttons down there? Or would that be confusing? 
screen shot 2016-10-01 at 12 39 46

**Comment by dhowe** [comment]
I would first try adding vertical space and/or a horizontal line to separate the 2 sections

**Comment by mushon** [comment]
I suggest we float it to the right, like we do it in the 3rd party filters tab (and show both buttons only after a change was made):
image

**Comment by dhowe** [comment]
the EFF filter list is not user-adjustable

**Comment by leoneckert** [comment]
@dhowe you mean the checkbox? it's not clickable, should it?

**Comment by leoneckert** [comment]
here is one option with more space between the two:
screen shot 2016-10-04 at 19 02 14

**Comment by leoneckert** [comment]
about @mushon 's suggestion I am not sure exactly if I understand it right. you mean like in my mockup below with both the apply and the revert button (or only apply needed?) in that spot, but only showing up when changes are made / only when they turn blue..?

suggestion

**Comment by mushon** [comment]
Yes, the screenshot is correct but just like in the 3rd party filters tab, we shouldn't show these buttons unless an action was made.

Thanks.

**Comment by dhowe** [comment]
No, the spacing and the h-line are not in the correct place. The buttons (Apply and Revert) and the text "Your list of host names... " apply ONLY to the bottom text-area, and have nothing to do with the EFF stuff at the top. They belong BELOW the space/line.

**Comment by mushon** [comment]
I agree the space is not needed but why not use the apply/revert for the full page and show it only if a change has been made?

**Comment by dhowe** [comment]
It seems strange to me to put an 'apply' button next to a control that can not be manipulated by the user

**Comment by leoneckert** [comment]
okay, so the pull request below now looks like the screenshot below (optionally with the line instead). I'll make a new PR with @mushon 's suggestion to compare.

screen shot 2016-10-05 at 17 47 36

**Comment by dhowe** [comment]
This seems clearer to me (and also matches the ublock interface which some users may be familiar with).

**Comment by dhowe** [comment]
@leoneckert add the horizontal rule and I'll merge this

**Comment by leoneckert** [comment]
I assume you mean the horizontal line in your last comment, @dhowe ? if you merge this right now it looks like:

screen shot 2016-10-09 at 18 05 49

**Pull request merged**
