### PR TITLE
Fix misprint(?) that cause unhandeled exception

### PR DESCRIPTION
**Pull request by SkeLLLa**
Hello. I don't know how to reproduce an error, but the error happend to me few times. As far as I can see there's misprint here.

### CODE REVIEW

**Comment by greysonevins** [comment]
@SkeLLLa it looks like you may be correct! Thank you. Before we merge, @dhowe @cqx931  should we refactor the whole traffic.js file with instances of `refererIdx` to `refIdx` (or vice versa) for consistency?

**Comment by dhowe** [comment]
good -- but that is a ublock file, so lets keep any changes minimal

**Comment by SkeLLLa** [comment]
@dhowe, yes, I know. I've checked ublock sources before to ensure that mistake was in added methods for AdNauseam.

**Comment by dhowe** [comment]
not a bad idea... we generally break out code into new /js/adn/ files after it exceeds a certain size, but might be worth considering for traffic.js, though it would still need to include the calls into this 2nd file (unless I am misunderstanding)...

**Pull request merged**
